api/urls.py
from django.urls import path 
from . import views 

app_name = "api"

urlpatterns = [
    path('', views.api_overview, name="overview"),
    path('blogs/', views.list_blog, name="blogs-list"),
    path('blogs/<int:id>', views.blog_detail, name="blog-detail"),
]

auth_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("authsys.urls")),
    path("", include("blog.urls")),
    path("api/", include("api.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authsys/urls.py
from django.urls import path 
from . import views 

app_name = "authapp"

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register_user, name="register"),
    path('logout/', views.logout_user, name="logout"),
]

blog/urls.py
from django.urls import path 
from . import views 
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create_post, name="create"),
    path('update/<int:post_id>', views.update_post, name="update"),
    path('delete/<int:post_id>', views.delete_post, name="delete"),
    path('search/', views.SearchPost.as_view(), name="search"),
    path('post/<int:post_id>', views.detail, name="detail"),
    path('comment/<int:post_id>', views.add_comment, name="comment"),
    path('like/<int:post_id>', views.like_post, name="like"),
    path('rss/feed', views.LatestPostsFeed(), name="latest_rss"),
    path('dislike/<int:post_id>', views.dislike_post, name="dislike"),
    path('<int:user_id>/profile', views.user_profile, name="profile"),
    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=20)

class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    liked_by = models.ManyToManyField(User, related_name="liked_posts", blank=True)
    disliked_by = models.ManyToManyField(User, related_name="disliked_posts", blank=True)
    # temp = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(blank=True)
    tags = models.ManyToManyField(Tag)
    # comments = 
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=200)
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'post'], name="unique_comment_per_blog")
        ]

    def __str__(self):
        return self.content 

blog/forms.py
from django import forms 
from .models import Post 

class PostCreationForm(forms.ModelForm):
    tags = forms.CharField(max_length=20)
    class Meta:
        model = Post 
        fields = ["title", "content", "image"]

        

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from .forms import PostCreationForm
from .models import Post, Comment, Tag
from django.views import View
from django.db.models import Q 
from django.contrib.auth.models import User 
from django.contrib.auth.decorators import login_required
from django.contrib.syndication.views import Feed 
from rest_framework.decorators import api_view
from rest_framework.response import Response 

# Create your views here.
def index(request):
    posts = Post.objects.all().order_by("-created")
    return render(request, "blog/index.html", {"posts":posts})

@login_required(login_url="authapp:index")
def create_post(request: HttpRequest):
    form = PostCreationForm()
    if request.method == "POST":
        form = PostCreationForm(request.POST, request.FILES)
        if(form.is_valid()):
            post:Post = form.save(commit=False)
            post.user = request.user 
            post.save()
            tags = form.cleaned_data['tags']
            tag_list = tags.split(' ')
            for tag in tag_list:
                print(tag)
                tag = tag.strip()
                tag_obj, created = Tag.objects.get_or_create(name=tag)
                if created:
                    tag_obj.save()
                post.tags.add(tag_obj)
            
            return redirect("blog:index")
    return render(request, "blog/newpost.html", {"form":form}) 

@login_required(login_url="authapp:index")
def delete_post(request, post_id):
    posts = Post.objects.all()
    post = Post.objects.get(pk=post_id)
    post.delete()
    return redirect("blog:index")

@login_required(login_url="authapp:index")
def update_post(request:HttpRequest, post_id:int):
    post = Post.objects.get(pk=post_id)
    
    form = PostCreationForm(instance=post)
    if request.method == "POST":
        form = PostCreationForm(request.POST, request.FILES, instance=post)
        if(form.is_valid()):
            post = form.save(commit=False)
            post.user = request.user 
            post.save()
            return redirect("blog:index")
    return render(request, "blog/updatepost.html", {"post_id":post_id, "form":form}) 

class SearchPost(View):
    def get(self, request):
        data = request.GET.get('q', '')
        tag = get_object_or_404(Tag, name=data)
        posts = Post.objects.filter(Q(title__icontains=data)|Q(content__icontains=data)).order_by("-created")

        return render(request, "blog/index.html", {"posts":posts})

def detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    user_has_commented = Comment.objects.filter(user=request.user, post=post).exists() if request.user.is_authenticated else True 
    user_has_liked = post.liked_by.filter(id=request.user.id).exists() if request.user.is_authenticated else True
    user_has_disliked = post.disliked_by.filter(id=request.user.id).exists() if request.user.is_authenticated else True
    
    return render(request, "blog/detail.html", {"post":post, "user_has_commented":user_has_commented, "user_has_liked":user_has_liked, "user_has_disliked":user_has_disliked})


@login_required(login_url="authapp:index")
def add_comment(request, post_id):
    post = Post.objects.get(pk=post_id)
    comment =Comment.objects.create(user=request.user, post=post, content=request.POST.get('comment', ''))
    comment.save()
    return redirect("blog:detail", post_id)

@login_required(login_url="authapp:index")
def like_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if(post.liked_by.filter(id=request.user.id).exists()):
        return HttpResponse("What the hell?")
    else:
        post.liked_by.add(request.user)
        return redirect("blog:detail", post_id)

@login_required(login_url="authapp:index")
def dislike_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if(post.disliked_by.filter(id=request.user.id).exists()):
        return HttpResponse("Why the hell?")
    else:
        post.disliked_by.add(request.user)
        return redirect("blog:detail", post_id)

@login_required(login_url="authapp:index")
def user_profile(request, user_id):
    user = User.objects.get(id=user_id)
    # avatar = get_thumbnailer(user.profile.profile_thumbnail).get_thumbnail({'size': (50, 50), 'crop': True})
    posts = Post.objects.filter(user=user)
    user_joined = user.date_joined.strftime('%B %Y')
    return render(request, "blog/profile.html",{'user':user, 'posts':posts, 'date_joined':user_joined})

class LatestPostsFeed(Feed):
    title = 'Latest Blog Posts'
    link = '/blog/'
    description = 'This is the latest feed of posts'

    def items(self):
        return Post.objects.order_by("-created")[:5]
    
    def item_title(self, item):
        return item.title 
    
    def item_description(self, item):
        return item.content 
    
    def item_link(self, item):
        return '/blog/post/{}'.format(item.id)

templates/blog/detail.html
{% extends 'blog/index.html' %}

{% block content %}
    <h2>{{ post.title }} </h2>
    <span>{{ post.liked_by.all.count }} likes </span> &nbsp;
    <span>{{ post.disliked_by.all.count }} dislikes </span>
    {% if request.user.is_authenticated and not user_has_liked %}
        <a href="{% url 'blog:like' post.id %}"> Like this post </a> &nbsp;
    {% endif %}
    {% if request.user.is_authenticated and not user_has_disliked %}
        <a href="{% url 'blog:dislike' post.id %}"> Dislike this post </a> &nbsp;
    {% endif %}
    <hr>
    <p>{{ post.content }} </p>
    <h3>Tags</h3>
    <ul>
        {% for tag in post.tags.all %}
            <li>{{ tag.name }} </li>
        {% endfor %}
    </ul>
    {% if post.image.url != None %}
    <img src="{{ post.image.url }}" >
    {% endif %}
    

    <h3> Comments </h3><hr>
    {% for comment in post.comments.all %}
        <div>
            <strong>{{comment.user.username}}: </strong>
            <span>{{ comment.content }} </span>
           
        </div>
        <br>
    {% endfor %}

    {% if request.user.is_authenticated and not user_has_commented %}
        <form action="{% url 'blog:comment' post.id %}" method="post">
            {% csrf_token %}
            <label for="comment">Add a Comment </label>
            <input type="text" name="comment" required>
            <input type="submit" value="Add">
        </form>
    {% endif %}
{% endblock content %}

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts - Djanger</title>
    
    <script type="text/javascript">
      function conf(){
        var c = confirm("Are you sure about that?")
        var s = document.getElementById("del")
        if(c == false){
          s.href = "#"
        }
      }
      
    </script>
</head>
<body>
    {% block header %}
    <div>
        <h1><a href="{% url 'blog:index' %}">Djanger </a></h1>
        {% if request.user.is_authenticated %}
        <span>{{ request.user.username }}</span>
        <span><a href="{% url 'authapp:logout' %}">Logout</a></span><br>
        <span><a href="{% url 'blog:profile' request.user.id %}"> Profile </a> </span>
        {% else %}
        <span><a href="{% url 'authapp:register' %}">Register</a></span>
        <span><a href="{% url 'authapp:index' %}">Login</a></span> <br>
        {% endif %}
        <form action="{% url 'blog:search' %}">
          <input type="text" name="q">
          <span><input type="submit" value="Search"></span>
        </form>
    </div>
    {% endblock header %}
    {% block content %}
    <h2>Posts</h2><hr> {% if request.user.is_authenticated %}<span> <a href="{% url 'blog:create' %}">Create </a> </span>{% endif %}
    {% for post in posts %}
      <div>
        <h3><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>
        <span>By {{ post.user.username }} on {{ post.created }}</span>
        <br>
        <p>{{post.content}}</p>
        <span>{{ post.liked_by.all.count }} likes</span>
        {% if post.user == request.user %}
        <span> <a href="{% url 'blog:update' post.id %}">Update </a> </span> &nbsp;
        <span> <a href="{% url 'blog:delete' post.id %}" onclick="conf()" id="del">Delete </a> </span>
        {% endif %}
        <hr>
      </div>
    {% endfor %}
    {% endblock content %}
</body>
</html>

templates/blog/newpost.html
{% extends 'blog/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h2>Create Post </h2>
<hr>
<form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>
{% endblock content %} 

templates/blog/profile.html
{% extends "blog/index.html" %}
{% load thumbnail %}

{% block content %}
<h2>Your Profile </h2><hr>
<img src="{% thumbnail user.profile.profile_thumbnail 300x300 crop %}" alt="profile picture"><br>
<span> Member since {{ date_joined }} </span><br>
<h3>About</h3>
<p>{{ user.profile.bio }} </p>
<h3>Your Posts </h3>
{% for post in posts %}
    <div>
        <h4><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h4>
        <span>By {{ post.user.username }} on {{ post.created }}</span>
        <br>
        <p>{{post.content}}</p>
        <span>{{ post.liked_by.all.count }} likes</span>
        {% if post.user == request.user %}
        <span> <a href="{% url 'blog:update' post.id %}">Update </a> </span> &nbsp;
        <span> <a href="{% url 'blog:delete' post.id %}" onclick="conf()" id="del">Delete </a> </span>
        {% endif %}
        <hr>
    </div>
{% endfor %}

{% endblock content %}

templates/blog/updatepost.html
{% extends 'blog/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h2> Update Post </h2>
    <hr>
    <form action="{% url 'blog:update' post_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="update">
    </form>
{% endblock content %}